# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: dinaltest
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: serverless-typescript
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-typescript

provider:
  name: aws
  runtime: nodejs20.x
  environment:
     TWITTER_BEARER_TOKEN: ${env:TWITTER_BEARER_TOKEN}

functions:
  checkLike:
    handler: src/functions/checkLike.handler
    events:
      - httpApi:
          path: /check-like
          method: get
